import { type BillCategory } from '@/types';

export const BILL_CATEGORIES: BillCategory[] = [
  {
    id: 'electricity',
    name: 'Electricity',
    icon: 'Zap',
    color: '#FFB800',
    gradient: 'from-amber-500 to-orange-500',
    description: 'Pay electricity bills from any power distributor instantly',
    consumerNumberLabel: 'Consumer Number / CA Number',
    consumerNumberPlaceholder: 'e.g. 100293847',
    consumerNumberPattern: '^[0-9]{9,12}$',
    providers: [
      { id: 'bses-delhi', name: 'BSES Rajdhani Delhi', logo: '⚡', category: 'electricity', upiId: 'bsesrajdhani@paytm' },
      { id: 'tata-power', name: 'Tata Power Delhi', logo: '⚡', category: 'electricity', upiId: 'tatapower@icici' },
      { id: 'adani-electricity', name: 'Adani Electricity Mumbai', logo: '⚡', category: 'electricity', upiId: 'adanielectricity@hdfc' },
      { id: 'best-mumbai', name: 'BEST Undertaking Mumbai', logo: '⚡', category: 'electricity', upiId: 'bestmumbai@paytm' },
      { id: 'msedcl', name: 'MSEDCL Maharashtra', logo: '⚡', category: 'electricity', upiId: 'msedcl@sbi' },
      { id: 'bescom', name: 'BESCOM Bangalore', logo: '⚡', category: 'electricity', upiId: 'bescom@axis' },
    ],
  },
  {
    id: 'water',
    name: 'Water',
    icon: 'Droplets',
    color: '#00B4D8',
    gradient: 'from-cyan-500 to-blue-500',
    description: 'Settle water board utility bills securely',
    consumerNumberLabel: 'Connection ID / Consumer Number',
    consumerNumberPlaceholder: 'e.g. K-98374-B',
    consumerNumberPattern: '^[A-Z0-9\\-]{5,15}$',
    providers: [
      { id: 'delhi-jal', name: 'Delhi Jal Board', logo: '💧', category: 'water', upiId: 'delhijalboard@sbi' },
      { id: 'bmc-water', name: 'BMC Water Mumbai', logo: '💧', category: 'water', upiId: 'bmcwater@hdfc' },
      { id: 'bwssb', name: 'BWSSB Bangalore Water', logo: '💧', category: 'water', upiId: 'bwssbwater@axis' },
      { id: 'hmwsb', name: 'HMWS&SB Hyderabad', logo: '💧', category: 'water', upiId: 'hmwsb@paytm' },
    ],
  },
  {
    id: 'gas',
    name: 'Piped Gas',
    icon: 'Flame',
    color: '#FF6B35',
    gradient: 'from-orange-500 to-red-500',
    description: 'Pay piped domestic cooking gas bills',
    consumerNumberLabel: 'Customer ID / BP Number',
    consumerNumberPlaceholder: 'e.g. 10098472',
    consumerNumberPattern: '^[0-9]{8,10}$',
    providers: [
      { id: 'igl', name: 'Indraprastha Gas Limited (IGL)', logo: '🔥', category: 'gas', upiId: 'igl@paytm' },
      { id: 'mahanagar-gas', name: 'Mahanagar Gas Limited', logo: '🔥', category: 'gas', upiId: 'mahanagargas@icici' },
      { id: 'adani-gas', name: 'Adani Total Gas', logo: '🔥', category: 'gas', upiId: 'adanitotalgas@hdfc' },
      { id: 'gujarat-gas', name: 'Gujarat Gas Company', logo: '🔥', category: 'gas', upiId: 'gujaratgas@sbi' },
    ],
  },
  {
    id: 'mobile',
    name: 'Mobile Recharge',
    icon: 'Smartphone',
    color: '#7209B7',
    gradient: 'from-violet-500 to-purple-600',
    description: 'Instant prepaid recharges or postpaid bill payments',
    consumerNumberLabel: '10-Digit Mobile Number',
    consumerNumberPlaceholder: 'e.g. 9876543210',
    consumerNumberPattern: '^[6-9][0-9]{9}$',
    providers: [
      { id: 'jio', name: 'Reliance Jio', logo: '📱', category: 'mobile', upiId: 'jio@paytm' },
      { id: 'airtel', name: 'Bharti Airtel', logo: '📱', category: 'mobile', upiId: 'airtel@icici' },
      { id: 'vi', name: 'Vodafone Idea', logo: '📱', category: 'mobile', upiId: 'vi@hdfc' },
      { id: 'bsnl', name: 'BSNL Prepaid / Postpaid', logo: '📱', category: 'mobile', upiId: 'bsnl@sbi' },
    ],
  },
  {
    id: 'dth',
    name: 'DTH Recharge',
    icon: 'Tv',
    color: '#E91E8C',
    gradient: 'from-pink-500 to-rose-600',
    description: 'Recharge satellite TV subscriptions',
    consumerNumberLabel: 'Subscriber ID / Smart Card Number',
    consumerNumberPlaceholder: 'e.g. 1502938475',
    consumerNumberPattern: '^[0-9]{8,12}$',
    providers: [
      { id: 'tata-play', name: 'Tata Play (Tata Sky)', logo: '📺', category: 'dth', upiId: 'tataplay@paytm' },
      { id: 'dish-tv', name: 'Dish TV', logo: '📺', category: 'dth', upiId: 'dishtv@icici' },
      { id: 'airtel-dth', name: 'Airtel Digital TV', logo: '📺', category: 'dth', upiId: 'airteldth@hdfc' },
      { id: 'sun-direct', name: 'Sun Direct DTH', logo: '📺', category: 'dth', upiId: 'sundirect@sbi' },
      { id: 'd2h', name: 'Videocon d2h', logo: '📺', category: 'dth', upiId: 'd2h@axis' },
    ],
  },
  {
    id: 'broadband',
    name: 'Broadband',
    icon: 'Wifi',
    color: '#3B82F6',
    gradient: 'from-blue-500 to-indigo-500',
    description: 'Pay broadband and high-speed fiber internet bills',
    consumerNumberLabel: 'Account Number / User ID',
    consumerNumberPlaceholder: 'e.g. BB-98274-IND',
    consumerNumberPattern: '^[A-Za-z0-9\\-_/]{5,20}$',
    providers: [
      { id: 'jio-fiber', name: 'JioFiber Broadband', logo: '🌐', category: 'broadband', upiId: 'jiofiber@paytm' },
      { id: 'airtel-fiber', name: 'Airtel Xstream Fiber', logo: '🌐', category: 'broadband', upiId: 'airtelfiber@icici' },
      { id: 'act-fiber', name: 'ACT Fibernet', logo: '🌐', category: 'broadband', upiId: 'actfibernet@hdfc' },
      { id: 'hathway', name: 'Hathway Broadband', logo: '🌐', category: 'broadband', upiId: 'hathway@sbi' },
      { id: 'tata-play-fiber', name: 'Tata Play Fiber', logo: '🌐', category: 'broadband', upiId: 'tataplayfiber@axis' },
    ],
  },
  {
    id: 'lpg',
    name: 'LPG Cylinder',
    icon: 'FlameKindling',
    color: '#EF4444',
    gradient: 'from-red-500 to-red-700',
    description: 'Book and pay for domestic LPG gas cylinders',
    consumerNumberLabel: 'LPG ID / Registered Mobile Number',
    consumerNumberPlaceholder: 'e.g. 9876543210 or 17-digit LPG ID',
    consumerNumberPattern: '^[0-9]{10,17}$',
    providers: [
      { id: 'indane', name: 'Indane Gas (IOCL)', logo: '🔥', category: 'lpg', upiId: 'indanegas@paytm' },
      { id: 'bharat-gas', name: 'Bharat Gas (BPCL)', logo: '🔥', category: 'lpg', upiId: 'bharatgas@icici' },
      { id: 'hp-gas', name: 'HP Gas (HPCL)', logo: '🔥', category: 'lpg', upiId: 'hpgas@hdfc' },
    ],
  },
  {
    id: 'fastag',
    name: 'FASTag Toll',
    icon: 'Car',
    color: '#10B981',
    gradient: 'from-emerald-500 to-green-600',
    description: 'Recharge electronic highway toll cards',
    consumerNumberLabel: 'Vehicle Registration Number (no spaces)',
    consumerNumberPlaceholder: 'e.g. DL1CA1234',
    consumerNumberPattern: '^[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}$',
    providers: [
      { id: 'paytm-fastag', name: 'Paytm FASTag Recharge', logo: '🚗', category: 'fastag', upiId: 'paytmfastag@paytm' },
      { id: 'icici-fastag', name: 'ICICI Bank FASTag', logo: '🚗', category: 'fastag', upiId: 'icicifastag@icici' },
      { id: 'hdfc-fastag', name: 'HDFCBANK FASTag', logo: '🚗', category: 'fastag', upiId: 'hdfcfastag@hdfc' },
      { id: 'sbi-fastag', name: 'State Bank of India FASTag', logo: '🚗', category: 'fastag', upiId: 'sbifastag@sbi' },
    ],
  },
  {
    id: 'credit-card',
    name: 'Credit Card',
    icon: 'CreditCard',
    color: '#6366F1',
    gradient: 'from-indigo-500 to-violet-600',
    description: 'Pay credit card dues of any major bank',
    consumerNumberLabel: 'Last 4 digits of Card Number',
    consumerNumberPlaceholder: 'e.g. 4321',
    consumerNumberPattern: '^[0-9]{4}$',
    providers: [
      { id: 'hdfc-card', name: 'HDFC Bank Credit Card', logo: '💳', category: 'credit-card', upiId: 'hdfccard@hdfc' },
      { id: 'icici-card', name: 'ICICI Bank Credit Card', logo: '💳', category: 'credit-card', upiId: 'icicicard@icici' },
      { id: 'sbi-card', name: 'SBI Card', logo: '💳', category: 'credit-card', upiId: 'sbicard@sbi' },
      { id: 'axis-card', name: 'Axis Bank Credit Card', logo: '💳', category: 'credit-card', upiId: 'axiscard@axis' },
      { id: 'amex-card', name: 'American Express Card', logo: '💳', category: 'credit-card', upiId: 'amexcard@paytm' },
    ],
  },
  {
    id: 'insurance',
    name: 'Insurance Dues',
    icon: 'Shield',
    color: '#14B8A6',
    gradient: 'from-teal-500 to-cyan-600',
    description: 'Pay life, health, or vehicle insurance premiums',
    consumerNumberLabel: 'Policy Number',
    consumerNumberPlaceholder: 'e.g. LIC-9837482',
    consumerNumberPattern: '^[A-Za-z0-9]{8,15}$',
    providers: [
      { id: 'lic', name: 'Life Insurance Corporation (LIC)', logo: '🛡️', category: 'insurance', upiId: 'licindia@paytm' },
      { id: 'hdfc-life', name: 'HDFC Life Insurance', logo: '🛡️', category: 'insurance', upiId: 'hdfclife@hdfc' },
      { id: 'icici-prudential', name: 'ICICI Prudential Life', logo: '🛡️', category: 'insurance', upiId: 'iciciprulife@icici' },
      { id: 'sbi-life', name: 'SBI Life Insurance', logo: '🛡️', category: 'insurance', upiId: 'sbilife@sbi' },
    ],
  },
  {
    id: 'municipal',
    name: 'Municipal Taxes',
    icon: 'Building2',
    color: '#6366F1',
    gradient: 'from-indigo-500 to-blue-600',
    description: 'Pay property and other municipal tax dues',
    consumerNumberLabel: 'Property Tax ID / Assessment ID',
    consumerNumberPlaceholder: 'e.g. TAX-983472',
    consumerNumberPattern: '^[A-Z0-9\\-]{6,15}$',
    providers: [
      { id: 'mcgm', name: 'Municipal Corp of Greater Mumbai', logo: '🏛️', category: 'municipal', upiId: 'mcgm@icici' },
      { id: 'mcd', name: 'Municipal Corp of Delhi (MCD)', logo: '🏛️', category: 'municipal', upiId: 'mcddelhi@sbi' },
      { id: 'bbmp', name: 'Bruhat Bengaluru Mahanagara Palike', logo: '🏛️', category: 'municipal', upiId: 'bbmp@axis' },
    ],
  },
  {
    id: 'education',
    name: 'Education Fees',
    icon: 'GraduationCap',
    color: '#A855F7',
    gradient: 'from-purple-500 to-violet-600',
    description: 'Settle school, college, or university academic fees',
    consumerNumberLabel: 'Student Enrollment ID / Reg Number',
    consumerNumberPlaceholder: 'e.g. IITB-2024-ME032',
    consumerNumberPattern: '^[A-Za-z0-9\\-/]{6,20}$',
    providers: [
      { id: 'du', name: 'Delhi University Fee', logo: '🎓', category: 'education', upiId: 'dufees@sbi' },
      { id: 'iit-bombay', name: 'IIT Bombay Fee Collection', logo: '🎓', category: 'education', upiId: 'iitbfee@hdfc' },
      { id: 'bits-pilani', name: 'BITS Pilani fee counter', logo: '🎓', category: 'education', upiId: 'bitsfee@axis' },
      { id: 'vit', name: 'Vellore Institute of Technology', logo: '🎓', category: 'education', upiId: 'vitfees@paytm' },
    ],
  },
  {
    id: 'rent',
    name: 'Rent Payments',
    icon: 'Home',
    color: '#F43F5E',
    gradient: 'from-rose-500 to-pink-600',
    description: 'Transfer house rent directly to landlord UPI/bank account',
    consumerNumberLabel: 'Landlord UPI ID / VPA',
    consumerNumberPlaceholder: 'e.g. landlord@upi',
    consumerNumberPattern: '^.+@[a-zA-Z]{3,}$',
    providers: [
      { id: 'nobroker', name: 'NoBroker Rent Transfer', logo: '🏠', category: 'rent', upiId: 'nobrokerrent@icici' },
      { id: 'magicbricks', name: 'MagicBricks RentPay', logo: '🏠', category: 'rent', upiId: 'mbrent@hdfc' },
    ],
  },
];
